### ISSUE TITLE
error using internet explorer

### ISSUE THREAD

**Issue by jetinet** [francoisjacquet/rosariosis#109]
Hello!

I've just installed rosariosis (version 2.8.16) and it works fine. Except with Internet Explorer from Microsoft (does not depend which version - tried more of them). When i try to login i get the note : You must accept cookies to use RosarioSIS. 

Cookies are enabled! Works with firefox and chrome. The school im setting it up for only uses internet explorer.

Any suggestions?

**Comment by francoisjacquet** [comment]
Hello @jetinet,

Some tests have been run with RosarioSIS 2.8.16:
IE8: OK
IE8 + session.auto_start 1 (in php.ini): OK
IE11 + session.auto_start 1 (in php.ini): OK
Those Internet Explorers have default configuration.

In order to determine if the error is on the server side or on the 
browser side, please enter the online demo of RosarioSIS with IE and 
post here the result.

To access the demo, please consult: http://rosariosis.org/services/

**Comment by jetinet** [comment]
Hello!

I've just tried youre demo and it works with Internet Explorer. 
My Installation is on a Windows System (Server 2012) with WAMP (Version 2.5). 
Do you have any idea why my Installation only works with Chrome and Firefox ? 

Thank's for the help!

**Comment by francoisjacquet** [comment]
Alright, so this is not due to your Internet Explorer configuration.

A simple DuckDuckGo search gave me this result:
http://stackoverflow.com/questions/20089349/session-not-working-on-localhost-using-ie-9-and-virtual-host

Please post your solution here when you have one.

**Comment by abcsis** [comment]
What is the solution? I am having this problem for IE and safari. Please help. #151
