### ISSUE TITLE
Change Student/ User Naming Style from First Name/ Last Name to others

### ISSUE THREAD

**Issue by affiezaladnan** [francoisjacquet/rosariosis#120]
Hi,

Currently, RosarioSIS uses first name/ last name convention and display name as last name, first name convention. Is is possible to change this to other types of name convention such as patronymic/ single name etc?

Thanks

**Comment by francoisjacquet** [comment]
Hi @affiezaladnan ,

Changing those _First name_ / _Last name_ fields labels is not possible.

Nevertheless, you could add _Patronymic_ / _Single name_ fields as new _Student / User Fields_ (see corresponding menu entries in RosarioSIS).

Then you can have them displayed in the Expanded View listings and / or searchable by checking them in _Users > My Preferences > User / Student Fields_.

If you need more help configuring RosarioSIS, please contact us at http://www.rosariosis.org/services/

**Comment by affiezaladnan** [comment]
Thanks for your quick reply.

When adding users/ students, the mandatory fields include First Name and Last Name. When listing users/ students, the list would display names as lastname, firstname format. This is an issue for me since in my country, we use single name instead of first name, last name format.

How can this be changed/ modified?

**Comment by francoisjacquet** [comment]
@affiezaladnan the texts / labels such as "First Name", "Last Name" can be easily customized:
Simply create a new translation and adapt the texts you need.
For example, the [English Canadian translation](https://github.com/francoisjacquet/rosariosis/tree/mobile/locale/en_CA.utf8/LC_MESSAGES) does only bring few translations such as "Postal code" instead of "Zip code", "Province" instead of "State", etc.

Please consult this [tutorial to create a new translation](https://github.com/francoisjacquet/rosariosis/wiki/Localizing,-translate-RosarioSIS-with-Poedit).
