### ISSUE TITLE
What need I to do to access RosarioSIS from SmartPhones (like students or teachers smartphones)?

### ISSUE THREAD

**Issue by cursogalileu** [francoisjacquet/rosariosis#131]
I tried to use **localhost/rosariosis/rosariosis-2.8.26/index.php** with no success.

**Comment by danfelbm** [comment]
RosarioSIS's design is responsive, that means you actually don't need to do anything; simply resize your web browser's window size and you will notice it adapts accordingly. That means that when you use RosarioSIS through a smartphone's web browser like Chrome or CM Browser, it will show the mobile version of the platform.

**Comment by cursogalileu** [comment]
Thanks for your prompt answer. About smartphones: I have a smartphone
with Android and I tried typing
LOCALHOST/ROSARIOSIS/ROSARIOSIS-2.8.26/INDEX.PHP but this not executes.
It shows message "Página da Web não disponível" or "This page is
unavailable". What I need to type? Thanks once more. 

 Hugo Penido Gattoni 
 BELO HORIZONTE
 MINAS GERAIS
 BRASIL 

Em 2016-03-22 12:15, danfelbm escreveu: 

> RosarioSIS's design is responsive, that means you actually don't need to do anything; simply resize your web browser's window size and you will notice it adapts accordingly. That means that when you use RosarioSIS through a smartphone's web browser like Chrome or CM Browser, it will show the mobile version of the platform. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
 

Links:
------
[1]
https://github.com/francoisjacquet/rosariosis/issues/131#issuecomment-199860599

**Comment by danfelbm** [comment]
Hi there,

I believe you have installed RosarioSIS on your local machine using XAMPP or something similar, right?. If this is correct, then this web-server will only be available on the local machine where you installed it, unless you allow incoming connections through port 80 (most likely) and use your public IP instead of the localhost.

There is no way you can connect to your localhost from your smartphone if you haven't previously configured the web server to allow so. The best option you have right now is testing its responsiveness on your PC by resizing your browser's window or using the web browser's developer tools to simulate a mobile device:

For Chrome: https://developer.chrome.com/devtools/docs/device-mode
For Firefox: https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode
For Safari: http://www.htmlgoodies.com/beyond/webmaster/toolbox/article.php/3889011/Using-Safari-for-iPhone-iPad-and-iPod-Touch-Website-Testing.htm

... Or simply resize the browser's windows. That's exactly the same behaviour you would experience in a mobile device when using RosarioSIS.

Otherwise if you really need to test this on your Android, the best option you have is to contact with RosarioSIS at info@rosariosis.org and ask for the demo Url and credentials. You can also set it up on a shared hosting environment; or finally opening the required ports for your localhost to be available on the internet: http://stackoverflow.com/questions/822902/access-xampp-localhost-from-internet (although this isn't for novice users)

Kind regards.

**Comment by cursogalileu** [comment]
OK. I will try this. Thanks in advance.

**Comment by francoisjacquet** [comment]
@cursogalileu please be careful to add your solution to the _right_ issue.

> As I promised, here is problem solution to have smartphone accessing Rosario SIS on my PC:
> 1.- Go to Start and type cmd on your PC Windows
> 2.- On "DOS" screen goto to main directory (C:)
> 3.- type ipconfig
> 4.- Search results to find IPv4
> 5.- In front of IPv4 you could get the IP of your PC (something like 192.168.0.1 - not this value!)
> 6.- type on your SmartPhone: 192.168.0.1/rosariosis/rosariosis-2.8.26/index.php (remember to change the IP address for the value you found in front of IPv4).
> 7.- That´s All Folks!
> 
> I need to say "Thank you" to François Jacquet and "danflbm"!
> Best regards.
