### ISSUE TITLE
Missing requirements for PHP modules

### ISSUE THREAD

**Issue by dabest1** [francoisjacquet/rosariosis#136]
I am not able to load the index.php page and get the following error in /var/log/php-fpm/www-error.log:
PHP Fatal error:  Call to undefined function mb_internal_encoding() in /usr/share/nginx/html/Warehouse.php on line 85

It seems like php-mbstring module should be installed, but this is not listed in the install steps.
Ran:
yum install php-mbstring
service php-fpm restart
Installing the module leads to the next error:
PHP Fatal error:  Call to undefined function pg_connect() in /usr/share/nginx/html/database.inc.php on line 16
Ran:
yum install php-pgsql
service php-fpm restart

This fixed the issue and I got to the login page.

I am using:
PHP 5.3.29
PHP 5.3.29 (fpm-fcgi)
nginx/1.8.1

**Comment by danfelbm** [comment]
> This fixed the issue and I got to the login page.

Are you experiencing any issue?
https://www.rosariosis.org/download/ remember to meet the requirements prior to the installation.

**Comment by dabest1** [comment]
I was able to get it working after spending quite a bit of time looking for the problem.

I think the installation requirements or instructions need to be updated to include installation of above mentioned packages.

**Comment by francoisjacquet** [comment]
@dabest1 the _mbstring_ PHP ext generally comes installed with PHP by default (on Ubuntu & Debian servers), hence it is not specifically mentioned.
Regarding the _pgsql_ PHP ext, this one should be obvious since RosarioSIS requires PostgreSQL to work, please refer to the page mentioned by @danfelbm.

We cannot cover every case / configuration, as [stated here](https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL#L10). Those install instructions are valid for Ubuntu server. We hope that you will understand.

However, for your convenience, the _mbstring_ & _pgsql_ checks are performed by the [_diagnostic.php_](https://github.com/francoisjacquet/rosariosis/blob/mobile/diagnostic.php#L35) page.

Please refer to the appropriate [INSTALL](https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL#L98) for more information.

Cheers
