### ISSUE TITLE
Changing the naming style from Last Name/First Name to First Name/Last Name across the SIS?

### ISSUE THREAD

**Issue by mzjdev** [francoisjacquet/rosariosis#148]
Hi,

The region I live in uses the First Name/Last Name naming convention instead of Last Name/First Name. Is there a way to change it in all modules such as grades, reports, etc.

Regards.

**Comment by francoisjacquet** [comment]
Hi @mzjdev 

There is no way to change the full name convention (First name before Last name) within RosarioSIS for the moment.

**Comment by cursogalileu** [comment]
Sorry, this solution may be stupid, but I suppose it could be used: 

Student name HUGO PENIDO GATTONI 

Last name: HUGO 

First Name: GATTONI 

Middle name: P. 

ON REPORTS WE WILL HAVE: 

HUGO, P. GATTONI 

---

```
   HUGO PENIDO GATTONI
```

  GALILEU - NÚCLEO DE ESTUDOS
 31-9 9894-9392
 31- 4101-4799
 BELO HORIZONTE
 MINAS GERAIS
 BRASIL 

Em 2016-06-14 03:30, mzjdev escreveu: 

> Hi, 
> 
> The region I live in uses the First Name/Last Name naming convention instead of Last Name/First Name. Is there a way to change it in all modules such as grades, reports, etc. 
> 
> Regards. 
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

## Links:

[1] https://github.com/francoisjacquet/rosariosis/issues/148
[2]
https://github.com/notifications/unsubscribe/ARLBeVUzn1FsGl07xy5lsjGXyDvVcQnlks5qLkp-gaJpZM4I1ABd

**Comment by francoisjacquet** [comment]
@cursogalileu this solution (entering the first name in the "Last name" field and the last name in the "First name" field) may be a viable workaround if you use a [custom translation](https://github.com/francoisjacquet/rosariosis/wiki/Localizing,-translate-RosarioSIS-with-Poedit) where you translate "Last name" to "First name" and "First name" to "Last name".

One remark though: full names convention is not consistent and are sometimes presented as "First name Last Name" instead of "Last name, First name"...

**Comment by francoisjacquet** [comment]
Hello @mzjdev

We have good news!

The Display name option enhamcement was sponsored and comes with RosarioSIS 3.7, see issue #218

Please tell us if it works for you.
