### ISSUE TITLE
You must accept cookies to use RosarioSIS

### ISSUE THREAD

**Issue by abcsis** [francoisjacquet/rosariosis#152]
#151 #109

Please, there is no solution anywhere, and you are not helping. How am I suppose to provide more details? The screen only show this message, nothing else. Simply close down my case, and unable to reopen, so I open a new case.

**Comment by francoisjacquet** [comment]
Please provide more details to help us reproduce the problem: https://github.com/francoisjacquet/rosariosis/blob/mobile/CONTRIBUTING.md

**Comment by abcsis** [comment]
It's a fresh new installation, and when login using IE or safari, it just show this message:
"You must accept cookies to use RosarioSIS"

Cookies are enabled in IE and safari settings.

No problem when login using Firefox or Chrome. What other details you require? What happen to previous cases with this problem? It's a bug and you just close it?

**Comment by francoisjacquet** [comment]
We will require:
- Your RosarioSIS version
- Your browser versions
- Your server OS, web server, PHP, PostgreSQL versions
- And please first check if the _[diagnostic.php](https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL.md#installation-problems)_ page finds errors.

**Comment by abcsis** [comment]
RosarioSIS version: 2.9.3
Browser version: IE 8,9,10,11, Microsoft Edge, Safari 5
Server OS: Windows Server 2008 R2
Web server: Apache 2
PHP 5
PostgreSQL 9.5.3

**Comment by francoisjacquet** [comment]
Thank you for the details.

You configuration (Windows Server 2008) has not been [tested](https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL.md#rosariosis-student-information-system) and I personally do not have access to a Windows Server 2008.

Please note that this cookie issue could not be reproduced on a Windows 10 server (https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows) and IE 11.
It could not be reproduced either using a Linux server and IE 11, Safari 5.

As a server administrator, you now have the responsibility of its good configuration _prior_ to installing RosarioSIS. If you need support for Windows Server 2008, please contact Micro$oft.

You are also invited to switch to a server using free OS such as a GNU/Linux distribution.

**Comment by abcsis** [comment]
The server is fresh new install and got nothing extra configuration beside the installation guide given. However I install in a fresh new Windows 7 Windows 7 x64, the problem is still the same! Same message when try to login with IE. Worst now I login using Firefox, I can't even edit the school information and configuration!

**Comment by abcsis** [comment]
and btw, I check in diagnostic.php page, it show "Your RosarioSIS installation is properly configured.", so what is the problem/bug???

**Comment by francoisjacquet** [comment]
Alright, thank you for mentioning the problem is the same on Windows 7.

Now, if you will, we can play a game:
The rules are simple: you are going to spot the differences between your setup and [this tutorial](https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows), and this for _each_ step.

Reading bonus:
http://www.linuxquestions.org/questions/programming-9/php-session-not-working-in-chrome-and-ie-but-working-fine-in-firefox-4175507036/
https://www.litespeedtech.com/support/forum/threads/session-cookie-not-created-in-safari.2037/

Good luck.

**Comment by abcsis** [comment]
Yes, i use that tutorial to setup step by step, tried everything, problem still there.

Note: You must accept cookies to use ROSARIOSIS.

The url upon login in IE and show the above message:
http://localhost/index.php?locale=en_US.utf8&reason=cookie

Any way to bypass the cookie check?

**Comment by danfelbm** [comment]
Hello @abcsis 

Couldn't it be your web browser's cache?, if you deliberately access the URL using index.php?locale=en_US.utf8**&reason=cookie** it will force the error message, even if it isn't happening.

**If you have already tried the fixes proposed**, can you please clean your browser's cache and / or try from a different web browser?, making sure you only access _http://localhost/index.php_

Cookies should not be bypassed, it is the way RosarioSIS (and pretty much any website) creates sessions and a persistent experience when you log in.

At this point it seems a problem with Windows accepting cookies, since I followed the tutorial step by step on a Windows 7 x64 installation, and it worked as well :/
Googling about "cookies and windows server 2008" I found this:

http://msdn.microsoft.com/en-us/library/aa918417.aspx 
please check: "Privacy settings" and "Per site cookie handling"

Does it work?

Regards

**Comment by abcsis** [comment]
Have tried to clear cache, tried on different browsers on different PC, not deliberately access the URL. I'm providing the URL so as to troubleshoot. I'm not saying to bypass cookies, I meant to bypass the cookies **check** upon login, since the browsers, almost all browsers default settings are accepting cookies.

**Comment by francoisjacquet** [comment]
Hello @abcsis 

Thank you for the update,
Comparing your URL and the one you should have if you exactly followed the tutorial, we can already spot some interesting differences (namely the `8080` port and the `rosariosis` subfolder):
http://localhost**:8080**/**rosariosis/**
versus:
http://localhost/index.php

**Comment by thesmahesh** [comment]
If no web servers (like IIS, apache from wamp stack etc) are currently installed in a system, during installation wapp or wamp or lamp stack assigns the default port 80 to apache.
The default port is normally not required to be specified for accessing web pages, say for example, it is sufficient to enter:
`http://localhost`
rather than entering
`http://localhost:80`

If, on the other hand, a webserver is already installed in the system, it would have occupied port 80.
So when we try to install wapp/wamp/lamp stack, then it will detect port conflict and will prompt us to enter other ports for apache (like 8080, 8088) etc

In the above case, I assume there were no webservers installed previously resulting in the installation of wapp stack assigning the default port of 80 for apache rather than 8080

Moreover, the files to be served can either be placed in a subfolder when there are multiple projects/websites or they can reside in the root folder (default website) when there are not multiple projects/websites to be handled/served by apache.

**Comment by francoisjacquet** [comment]
Thank you @thesmahesh for your comment.

Now, could you confirm you have that same cookie problem when RosarioSIS is installed in the root folder and accessed from port 80?

**Comment by thesmahesh** [comment]
My Environment
Windows 10 64 bit
wapp statck with php 5.6
postgresql 9
Rosariosis 2.9.3

**Some findings based on my above environment**

**rosariosis in subfolder (eg http://localhost/rosariosis)**
no cookie issue in firefox, chrome, opera, edge, IE 11

**rosariosis in root folder (eg http://localhost)**
no cookie issue in firefox, chrome, opera
cookie issue in edge, IE 11

Based on the above, i could presume (with my limited knowledge and logic), Rosariosis files residing in the root folder of apache raises cookie error in Internet Explorer 11 and Edge browsers.
I would request the original poster to kindly move the Rosariosis files into a subfolder and provide us with the feedback.

Thanks and Regards

**Comment by francoisjacquet** [comment]
Thank you @abcsis for the update. I think we have pinned down the bug.

This bug with PHP cookies on `localhost` has been documented:
http://stackoverflow.com/questions/16779204/unable-to-read-cookie-in-php-on-localhost#16779624
http://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain#answer-1188145

I did try to prevent it by setting the domain to an empty string: `''`, see https://github.com/francoisjacquet/rosariosis/blob/mobile/Warehouse.php#L103 and http://php.net/session_set_cookie_params

Some say the domain may be set to `false`.
Could you please update your `Warehouse.php` file on line 103:
`session_set_cookie_params( 0, $cookie_path, false, false, true );`
And tell us if it fixes the issue?

**Comment by abcsis** [comment]
@thesmahesh No problem when put into subfolder. Thanks for the above clarification, it is very common to use the default port when no other web application using port 80 and host it in root folder, I don't understand what is the significant difference.

@francoisjacquet Issue not solve after updating the warehouse.php and restart webserver. Any idea how to fix the issue by hosting in root folder? I have tried to edit the apache conf to point the default directory to the subfolder, same issue as well.

**Comment by francoisjacquet** [comment]
Hello @abcsis , @thesmahesh , @danfelbm 

Thank you for helping make RosarioSIS better.

@abcsis please update the `Warehouse.php` file using this commit: https://github.com/francoisjacquet/rosariosis/commit/cdfb2f0b5dcb155cda15c509853517e3ba7c06fb
And confirm the issue is solved in IE when calling RosarioSIS from `localhost`

Thank you

**Comment by abcsis** [comment]
@francoisjacquet Thank you so much, successfully login using IE and Edge now.
