### ISSUE TITLE
Is it compatible with PHP 7?

### ISSUE THREAD

**Issue by danfelbm** [francoisjacquet/rosariosis#163]
Hi there,

I'd like to know if you have tested it on PHP 7. I'd like to upgrade
Has it experienced any issues?

Regards

**Comment by francoisjacquet** [comment]
Hello @danfelbm 

I am using PHP7 daily to develop RosarioSIS, and this since a few months. Although my **tests concern a small portion of all the programs / modules** so far.
Note that I have only run into one fatal error which was fixed in [version 2.9.6](https://github.com/francoisjacquet/rosariosis/blob/mobile/CHANGES.md#changes-in-296)

That would be great if _you or someone else_ could proceed to some further testing (or already have in production on Ubuntu 16.04) and confirm RosarioSIS is compatible.

**Comment by danfelbm** [comment]
Hi there,
I saw your message earlier but didn't reply. I've enabled PHP 7 and so far I haven't experienced any issues.

I have another question. Is there any possibility for a setting to allow or disallow teachers Create activities on past marking periods? there are some that don't check they are indeed in the current marking period and end up creating assignments where they shouldn't...

Regards

**Comment by francoisjacquet** [comment]
Hello @danfelbm 

I am glad RosarioSIS is working with PHP7 for you so far.

Regarding the Assignments problem, please open a new issue.

**Comment by francoisjacquet** [comment]
Closed for inactivity.
