### ISSUE TITLE
Course section duplicate listing

### ISSUE THREAD

**Issue by Calculagator** [francoisjacquet/rosariosis#200]
There seems to be a minor display issue one of my test teachers noticed.
We are running version 3.4.2 and I was able to replicate the issue on the demonstration server.
Course sections/periods that meet on different periods on different days show up for teachers as multiple classes. 

<img width="927" alt="screen shot 2017-08-23 at 5 52 03 pm" src="https://user-images.githubusercontent.com/29800105/29640198-d48338dc-882b-11e7-8cfb-8dd9d4a54a2f.png">

For example, when my test course meets on Period 1 on Wednesday, Period 2 on Thursday and Friday, and Period 7 on Monday, the teacher will see three different entries in the dropdown menu where they select the active course section. All three of these are being generated for only a single course section. As far as I can tell, a teacher can safely pick any one of these for entering grades etc, but it's a little confusing for a teacher. It's especially confusing for a teacher who may actually teach multiple different course sections: two courses may end up with 4-8 list options the way our scheduling is set up.

**Comment by francoisjacquet** [comment]
Hello @Claculagator 

Thank you for reporting your experience with the course periods dropdown.

This approach, although not really intuitive as you remark, is due to the fact that RosarioSIS allows multiple periods for a class (whereas Centre/SIS or OpenSIS does not, hence the term "Course Period").

The only program, where having those period entries is useful, is the _Take Attendance_ program where attendance is taken by period.

We can update the dropdown so it only shows courses, and move the periods dropdown to the _Take Attendance_ program.

If you would like to have this new behaviour in the next release, you can sponsor the development at https://www.rosariosis.org/services/

**Comment by francoisjacquet** [comment]
Done in version 6.9.
