### ISSUE TITLE
student pictures do not show up

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#202]
Hi

I tried to add pictures to my students, but they just do not show up in the General info tab. Also, when I take attendance and I hover over the name the picture does not show up, but the name show up.

I checked the folder assets/StudentPhotos/2017
I found pictures renamed in numbers. 
The pictures were there.

**Comment by francoisjacquet** [comment]
Hello @abogadeer

Thank you for reporting the issue.
It has already been reported [issue #171](https://github.com/francoisjacquet/rosariosis/issues/171#issuecomment-324594539) and [on the forum](https://www.rosariosis.org/forum/d/6-student-photo/3)

Can you reproduce the problem on the [demo](https://rosariosis.org/demo/) site?
This issue seems to happen on Windows.

Could you please upload a screenshot of your `assets/StudentPhotos/2017` folder here?

Thank you.

**Comment by abogadeer** [comment]
Hi
I could not reproduce it on the demo site

This is a picture of the folder from my FTP client
![student pics](https://user-images.githubusercontent.com/29820341/30006721-8bab98ea-9107-11e7-9906-26c1e5d9db66.png)


My php version is 5.6.29
Postgre SQL version: 8.4.20
I think the OS is linux since I am using Cpanel

**Comment by francoisjacquet** [comment]
@abogadeer 

Thank you for the screenshot.
It shows photos were uploaded for students with ID 2 and 9, for school year 2017.
Now, this may be a permissions related problem: can the webserver (Apache or nginx, usually with `www-data` user) access / read the photos?

Could you please go to `http://[YOUR_DOMAIN]/[YOUR_ROSARIOSIS_FOLDER]/assets/StudentPhotos/2017/1.jpg` and tell us what you get?

**Comment by abogadeer** [comment]
I did not understand this part

> Now, this may be a permissions related problem: can the webserver (Apache or nginx, usually with www-data user) access / read the photos?

When I go to http://[YOUR_DOMAIN]/[YOUR_ROSARIOSIS_FOLDER]/assets/StudentPhotos/2017/1.jpg

after I modify my domain and folder, I get 403 error access denied

**Comment by francoisjacquet** [comment]
@abogadeer 

Sorry, the correct URL in your case should end with `2.jpg` or `9.jpg`, in order to call any of the 2 photos.

The file permissions (read, write and execute) are related to Linux users. Your webserver accesses the photos using (generally) the `www-data` user.
Good read on the subject: https://www.linux.com/learn/understanding-linux-file-permissions
By the way, your hosting provider should be able to help you with this issue. Just let us know what they did if they fix the issue!

**Comment by abogadeer** [comment]
@francoisjacquet 
I contacted my host and the support guy said that he fixed the permissions
I told him that I changed the permissions via FTP client and it did not work

He refused to give me further details on what he exactly did

Problem resolved

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

Thank you for your answer. Some shared hosting providers do limit the file permissions they allow (for security reasons):
- **755** (or lower) for directories
- **644** (or lower) for files

Now, when RosarioSIS creates a directory (for example, _assets/StudentPhotos/2017/_), permissions should be compliant with shared hosting providers restrictions.
