### ISSUE TITLE
Change Quarterly to Terminal

### ISSUE THREAD

**Issue by ekowmensah** [francoisjacquet/rosariosis#243]
STUDENT BASE ASSESSMENT (SBA) not compatible with Ghana System, how it be changed and also how can i change the calendar to Terms instead of Quarters

**Comment by francoisjacquet** [comment]
Hello @ekowmensah 

Please tell us more about the _Ghanan System_ and how it is not compatible with RosarioSIS?

To change the word "Quarters" so it displays "Terms" instead, you can for example create a new locale / translation named `en_GH.utf8`. Please refer to the wiki, [Localizing, translate RosarioSIS with Poedit](https://github.com/francoisjacquet/rosariosis/wiki/Localizing,-translate-RosarioSIS-with-Poedit).

**Comment by ekowmensah** [comment]
OK. Ghana Education System has these:
1. Academic Year
2. Three (3) Terms in an Academic Year
3. School Base Assessment. Check demo here: ( https://demo.dtechghana.com/serp/ )

i'll be glad if the system could be customized to have those features in the ref link i've provided above


thank you!

**Comment by francoisjacquet** [comment]
Hello @ekowmensah,

I must admit I am not familiar with School Based Assessment and read the [Wikipedia article](https://en.m.wikipedia.org/wiki/School-based_assessment).

This system tries to focus on continuous assessment instead of pressurizing students with final exams, as for evaluation and grading concerns.

Still, could you please elaborate on how School Based Assessment differs from Student Based Assessment in respect to RosarioSIS requirements and/or limitations you may have experienced?

**Comment by ekowmensah** [comment]
I SENT YOU A DEMO LINK TO VIEW.

**Comment by francoisjacquet** [comment]
Closed for inactivity.
