### ISSUE TITLE
You cannot take attendance for this period on this day.

### ISSUE THREAD

**Issue by gondas33** [francoisjacquet/rosariosis#256]
Hello!
Just tested the attendance on the demonstration as I had problems on my system

I've created a course period for teacher Jose on 'default school' , Q1 with take attendance checked.

After that I've logged in into user: jose , pw: masina123 , went to Attendance->Take attendance and I got as an error message:  Warning: You cannot take attendance for this period on this day.

Any idea why this is happening? I tried tracing the issue in the code but couldn't find out much.

Thank you!

**Comment by francoisjacquet** [comment]
Hello @an4rei 

This is because November 22 2019 is after the end date of Quarter 1: 
![image](https://user-images.githubusercontent.com/4723501/69440229-b85b0280-0d48-11ea-9444-aa6c4747ca9e.png)

Next time please open your issue at [GitLab](https://gitlab.com/francoisjacquet/rosariosis/issues), or post on the [forum](https://www.rosariosis.org/forum/), as this is more of a question.
