### ISSUE TITLE
2 php error messages - installed using cPanel method

### ISSUE THREAD

**Issue by rkanka21** [francoisjacquet/rosariosis#268]
diagnostics says:
Error: PHP extensions: RosarioSIS relies on the pgsql (PostgreSQL) extension. Please install and activate it.

I installed and activated using easyapache4 in whm, but still get message.

also, when I log in to rosariosis, first message I see is "Warning Warning: passthru is disabled in your PHP configuration.
z"

Any suggestions?
thank you!

**Comment by francoisjacquet** [comment]
Hello @rkanka21 

Could you please post a screenshot of your php.ini showing your server has the pgsql extension activated?

The warning is because the _Database Backup_ program uses the `passthru()` function, and your php.ini disables it.

Please remember to open your issues at [GitLab](https://gitlab.com/francoisjacquet/rosariosis/-/issues/)!

**Comment by francoisjacquet** [comment]
Closed for inactivity.
